version: '3.8'

services:
  backend:
    build:
      args:
        ENVIRONMENT: prod
    restart: always
    env_file:
      - ../../.env.prod
    environment:
      - DJANGO_ENV=prod
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  frontend:
    build:
      args:
        ENVIRONMENT: production
      target: production
    restart: always
    env_file:
      - ../../.env.prod
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  server:
    build:
      args:
        ENVIRONMENT: prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../server/ssl:/etc/nginx/ssl
      - static_volume:/static
      - media_volume:/media
    env_file:
      - ../../.env.prod
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    build:
      args:
        ENVIRONMENT: prod
    restart: always
    env_file:
      - ../../.env.prod
    environment:
      - MYSQL_ENV=prod
    volumes:
      - db_prod_data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure

  cache:
    build:
      args:
        ENVIRONMENT: prod
    restart: always
    env_file:
      - ../../.env.prod
    environment:
      - REDIS_ENV=prod
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - cache_prod_data:/data
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_prod_data:
  cache_prod_data:
  static_volume:
  media_volume:
